name: Test and Lint on test branch

on:
  push:
    branches:
      - test  # Trigger on pushes to the test branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Define the Node.js version to test against

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures all branches are fetched

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Run lint
    #   run: npm run lint

    - name: Run tests
      run: npm test

